CREATE DATABASE DESAFIO BOOTCAMP;
USE DESAFIO BOOTCAMP;

CREATE TABLE CLIENTE
(
   ID_CLIENTE int PRIMARY KEY NOT NULL,
   NOME_CLIENTE varchar(60) NOT NULL,
   ENDERECO varchar(60) NOT NULL,
   NUMERO varchar(10) NOT NULL,
   ID_CIDADE int NOT NULL,
   CEP varchar(9) NOT NULL
); 

CREATE TABLE CIDADE
(
   ID_CIDADE int PRIMARY KEY NOT NULL,
   NOME_CIDADE varchar(60) NOT NULL,
   UF varchar(2) NOT NULL
);

CREATE TABLE VENDAS 
(
  NUM_VEND int PRIMARY KEY NOT NULL,
  DATA_VEN datetime NOT NULL,
  ID_CLIENTE int NOT NULL,
  ID_VENDEDOR int NOT NULL,
  STATUS char(1) NOT NULL
);

CREATE TABLE VENDEDORES 
(
  ID_VENDEDOR int PRIMARY KEY NOT NULL,
  NOME_VENDEDOR varchar(60) NOT NULL,
  SALARIO decimal(10,2) NOT NULL
);

CREATE TABLE VENDA_ITENS
(
  NUM_VEND int NOT NULL,
  NUM_SE int NOT NULL,
  ID_PROD int NOT NULL,
  QDTE decimal(10,2) NOT NULL,
  VAL_UNI decimal(10,2) NOT NULL,
  VAL_TOT decimal(10,2), 
  PRIMARY KEY (NUM_VEND, NUM_SE)
);

CREATE TABLE PRODUTOS
(
  ID_PROD int PRIMARY KEY NOT NULL,
  NOME_PROD varchar(50) NOT NULL,
  ID_CATEGORIA int NOT NULL,
  ID_UNIDADE varchar(3) NOT NULL,
  PRECO decimal(10,2) NOT NULL
);

CREATE TABLE CATEGORIA 
(
  ID_CATEGORIA int PRIMARY KEY NOT NULL,
  NOME_CATEGORIA varchar(20) NOT NULL
);

CREATE TABLE UNIDADE
(
  ID_UNIDADE varchar(3) PRIMARY KEY NOT NULL,
  DESC_UNIDADE varchar(25) NOT NULL
);

ALTER TABLE CLIENTE 

   ADD CONSTRAINT fk_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE);
   
ALTER TABLE VENDAS

   ADD CONSTRAINT fk_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE VENDAS

   ADD CONSTRAINT fk_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES (ID_VENDEDOR);

ALTER TABLE VENDA_ITENS

   ADD CONSTRAINT fk_VEND FOREIGN KEY (NUM_VEND) REFERENCES VENDAS (NUM_VEND);

ALTER TABLE VENDA_ITENS

   ADD CONSTRAINT fk_PROD FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS (ID_PROD);

ALTER TABLE PRODUTOS

   ADD CONSTRAINT fk_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA);

ALTER TABLE PRODUTOS

   ADD CONSTRAINT fk_UNIDADE FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE (ID_UNIDADE);

