--EXER 3
SELECT C.NOME_CLIENTE, P.NOME_CIDADE, P.UF
FROM CLIENTE AS C
JOIN CIDADE AS P ON C.ID_CIDADE = P.ID_CIDADE;

--EXER 4

SELECT P.ID_PROD, P.NOME_PRODUTO, C.NOME_CATEGORIA, P.PRECO
FROM PRODUTOS AS P
JOIN CATEGORIA AS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
WHERE 10 <= P.PRECO AND P.PRECO <=1500;

--EXER 5

SELECT P.ID_PROD, P.NOME_PRODUTO, C.NOME_CATEGORIA, P.PRECO as PRECO,
         CASE
		      WHEN PRECO < 500 THEN 'preco abaixo de 500'
			  WHEN PRECO >= 500 AND PRECO <= 1000 THEN 'preco entre 500 e 1000'
			  WHEN PRECO > 1000 THEN 'preco acima de 1000'
			  END AS FAIXA_DE_PRECO
FROM PRODUTOS AS P
JOIN CATEGORIA AS C ON P.ID_CATEGORIA = C.ID_CATEGORIA;
